- conda_package_handling/conda_fmt.py
- news/simplify_conda_pkg_info
- tests/test_api.py
This goes with https://github.com/conda/conda/pull/8639/ and https://github.com/conda/conda-build/pull/3500
In those PR's, we move the new .conda format to its own key in repodata, ``packages.conda``.  That allows us to use the same keys (size, md5, sha256) for either file type.
We also ditch the inner sha256 here, because that's really for package signing, and the inner sha256 doesn't add anything there.
> simply package info for .conda files

- conda_package_handling/tarball.py
https://ci.appveyor.com/project/ContinuumAnalyticsFOSS/conda-build/builds/24546103/job/ldw184ysl3bca1um#L3926
I'm pretty sure the problem is that the "out_fn" is being passed in as an absolute path, which when joined with tmpdir becomes just the value of "out_fn"
```
>>> os.path.join('/Users/msarahan/code', '/Users/msarahan/Downloads')
'/Users/msarahan/Downloads'
```
> fix strange path overlaps on Windows

- src/conda_package_handling/api.py
- src/conda_package_handling/exceptions.py
- tests/test_api.py
so that clients don't need to import libarchive directly to handle its exceptions
> add exception

- src/conda_package_handling/conda_fmt.py
- src/conda_package_handling/tarball.py
Still seeing obnoxious permission errors on CI.  Let's try just getting rid of the temporary files and write straight to the real output file path.
> remove tempfile renaming.  Write directly.

- src/conda_package_handling/conda_fmt.py
- src/conda_package_handling/utils.py
This sets the default dir for TemporaryDirectory to cwd.  This hopefully avoids the permissions problems we've been seeing with appveyor and azure, I think because they're split across two filesystems.
This also cleans up the temporary .zst files, which in 1.3.8 were being left around, making a mess.
> default tempdir location to nested in cwd, add back some tempdir usage

- src/conda_package_handling/api.py
- src/conda_package_handling/cli.py
- src/conda_package_handling/exceptions.py
- src/conda_package_handling/utils.py
- src/conda_package_handling/validate.py
This still needs a test.  We've seen some corrupt files from earlier iterations of CPH.  This should help us test files and also make sure we don't release further corrupt files.
> add a verification step in conversion.  Match file presence and size

- src/conda_package_handling/archive_utils_c.c
Open file that are included in the archive in binary mode.  On Window
the default is text mode where CRLF are converted to LF resulting in
potentially corrupt files being included in the archive.
> open files to add to archive in binary mode

- news/fix_null_pointer
- src/conda_package_handling/archive_utils_c.c
- src/conda_package_handling/archive_utils_cy.pyx
In `copy_data`, the error could also come from the reader and not just from the writer. Check for this case to avoid returning a NULL error string.
Fixes https://github.com/conda/conda/issues/9414
> Handle incomplete archives correctly

- .travis.yml
- tests/test_api.py
Travis-CI has added support for ARM64. Added ARM64 job in Travis-CI. 
Updated the tests/test_api.py to update the date as the test was failing rather than skipping.
> Adding Travis-Ci Support For Arm64

- news/out_folder.rst
- src/conda_package_handling/cli.py
> BUG not all parsers have args.out_folder

- .travis.yml
- conda.recipe/meta.yaml
- news/miscellaneous_fixes.rst
- src/conda_package_handling/api.py
- src/conda_package_handling/archive_utils_c.c
- src/conda_package_handling/tarball.py
- tests/test_api.py
@mingwandroid could you take a look at this... fallback implemented as requested. `size_t` fix resolves #71. 
I don't know the details of seeking in archives well enough to work it what is minimally required to trigger this bug and so reproduce it in a sensible way for regression testing. If I used `fallocate` for a few files of a GB to create a sufficiently large archive it still did not trigger the observed error. Nevertheless, the archive shared in #71 was sufficient to reproduce and confirm the fix for the bug.
I think I fixed an issue with Travis CI... I will debug if my hope is misplaced.
> Add miscellaneous fixes

- src/conda_package_handling/conda_fmt.py
- src/conda_package_handling/tarball.py
- src/conda_package_handling/utils.py
Compute package hashes in threads. The time taken is slightly longer than the time taken to do the slowest (sha256) hash. In my testing of a partial mirror this was the difference between 6.78s in `utils._checksum` to 4.60s in `utils.checksums`.
It's also possible to `open()` the file only once and submit each block to each thread, but that is harder to get right and it doesn't save much time to avoid the extra `open()`.
The buffer size doesn't seem to affect the timing much.
> compute package hashes in threads

- news/fix-44
- src/conda_package_handling/api.py
- src/conda_package_handling/conda_fmt.py
Before:
```python
In [1]: import conda_package_handling.api
...: !rm /tmp/ripgrep-13.0.0-habb4d0f_1.conda
...: conda_package_handling.api.transmute(
...:     "/home/cburr/miniconda3/pkgs/ripgrep-13.0.0-habb4d0f_1.tar.bz2",
...:     ".conda",
...:     out_folder="/tmp",
...: )
File ~/miniconda3/envs/diracos2-env-2/lib/python3.10/site-packages/conda_package_handling/api.py:107, in _convert(fn, out_ext, out_folder, **kw)
105 errors = ""
106 if not _os.path.lexists(out_fn) or ('force' in kw and kw['force']):
--> 107     with _TemporaryDirectory(prefix=out_folder) as tmp:
108         try:
109             extract(fn, dest_dir=tmp)
File ~/miniconda3/envs/diracos2-env-2/lib/python3.10/site-packages/conda_package_handling/utils.py:309, in TemporaryDirectory.__init__(self, suffix, prefix, dir)
308 …
```
> Fix setting base directory for creation of TemporaryDirectory

- news/sort-info-first.rst
- src/conda_package_handling/tarball.py
- tests/test_api.py
This old feature didn't work as intended, and `info/` appeared to be distributed randomly through the `.tar.bz2'. Fixes #101 
Will info start with `info\` (different os.path.sep) on Windows, in this function?
> Sort info first

- src/conda_package_handling/cli.py
Similar to what was done conda-build in https://github.com/conda/conda-build/pull/4467 
We should have a way of passing the zstd compression level to `cph transmute`
> Support setting the zstd compression level on the cli

- .github/workflows/CI.yaml
The minor modifications needed for renaming the default branch from master to main.
Xref: https://github.com/conda/conda/issues/11517
> Rename master to main

- src/conda_package_handling/api.py
- src/conda_package_handling/conda_fmt.py
- src/conda_package_handling/interface.py
- src/conda_package_handling/tarball.py
- tests/test_api.py
Test for #115
Can extract `/full/path/to/*.conda` but not `*.conda`
> fix, test extracting .conda given as relative path

- news/171-zstd-size
- src/conda_package_handling/conda_fmt.py
This should reduce memory usage on extract. We create a throwaway tar to find the size, then repeat to compress. The decompressor will be able to see the total decompressed size when allocating buffers.
We could return to creating temporary files to get the size, but this is simpler. Unsure how the timing compares.
#171
> calculate size in CondaFormat_v2.create()

- news/236-list-subcommand
- src/conda_package_handling/api.py
- src/conda_package_handling/cli.py
- src/conda_package_handling/conda_fmt.py
- src/conda_package_handling/interface.py
- src/conda_package_handling/streaming.py
- src/conda_package_handling/tarball.py
- tests/test_cli.py
Reuses `tarfile.Tarfile.list()` across .tar.bz2 and .conda artifacts. The unified interface with the tar generator makes it super easy!
This should help with inspecting artifact contents without having to pay for extraction. I picture this in post-conda-build reports in CI.
> add `cph list` subcommand

- .github/workflows/tests.yml
- .pre-commit-config.yaml
- news/python-update
- setup.py
- tests/memory_test.py
- tests/test_degraded.py
- Removes python 3.7
- Because `conda` no longer supports 3.7
- Adds python 3.10, 3.11, and 3.12
- All Supported by `conda` now
- I don't see any documentation that shows the python version range
In `python 3.12` this now raises the following warning:
> `DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.`
That relates to https://docs.python.org/3/library/tarfile.html#extraction-filters and specifically in 3.8->3.12 an non-specified filter will default to `fully_trusted` which may not be secure.  I went with *not* altering the behavior in this PR, but a followup issue should be filed/acted on to decide how we want to proceed.
This is a warning that is also present on …
> Update python matrix (add 3.10, 3.11, 3.12 - drop 3.7)

- news/205-getcwd
- news/206-getcwd
- pyproject.toml
- setup.cfg
- setup.py
- src/conda_package_handling/conda_fmt.py
- src/conda_package_handling/interface.py
- src/conda_package_handling/tarball.py
- tests/test_cli.py
Fix #205 (if caller passes output directory)
> Delay os.getcwd() call to function body

- news/248-use-zip64
- src/conda_package_handling/conda_fmt.py
Address same issue as https://github.com/conda/conda-package-streaming/issues/79 but when creating .conda directly (handled by conda-package-handling) , not converting from .tar.bz2 (handled by conda-package-streaming).
Fix #248 
Tested by running `dd if=/dev/urandom of=random bs=1M count=2048` and `cph c . /tmp/big.conda`, which will create a 2147533062-byte `pkg-big.tar.zst`, fail on the older code and succeed after this fix.
> Use force_zip64=True when directly creating .conda files

- news/253-components-list
- src/conda_package_handling/api.py
- src/conda_package_handling/cli.py
- tests/test_cli.py
Comes from https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/328
> Expose the `components` kwarg in the CLI and API

- news/251-extension-str-replace
- news/improve-typing
- src/conda_package_handling/api.py
- src/conda_package_handling/conda_fmt.py
- src/conda_package_handling/streaming.py
Fix #251 and another extension changer
Improve type annotations on an internal method
> Fix .conda extension replacement; improve typing
