conda/conda-package-handling

- conda_package_handling/__init__.py
- conda_package_handling/cli.py
- conda_package_handling/tarball.py
- conda_package_handling/utils.py
- news/version_info
> add version check output to cli

- .travis.yml
> [ci] Latest Miniconda3 is py37

- .github/pull_request_template.md
> Fix typo in GH PR template

- conda_package_handling/api.py
- conda_package_handling/conda_fmt.py
- conda_package_handling/tarball.py
- news/symlinks
> Fix missing symlinks

- .travis.yml
- MANIFEST.in
- tests/test_api.py
> Exclude tests manifest

- src/conda_package_handling/api.py
- src/conda_package_handling/cli.py
> handle exceptions in transmute and output list of failed files at end

- src/conda_package_handling/api.py
> don't print skip message for every skipped package

- news/add_api_get_folder_location
- src/conda_package_handling/api.py
- src/conda_package_handling/cli.py
- src/conda_package_handling/conda_fmt.py
- src/conda_package_handling/interface.py
- src/conda_package_handling/tarball.py
> add api function for getting default dest folder

- src/conda_package_handling/utils.py
> wrap tempdir cleanup more and warn when it fails

- .coveragerc
- .travis.yml
- appveyor.yml
- news/rm_rf
- src/conda_package_handling/api.py
- src/conda_package_handling/exceptions.py
- src/conda_package_handling/utils.py
- tests/test_utils.py
> port rm_rf from conda; use it for our custom TemporaryDirectory

- .gitattributes
> attempt to fix versioneer (was missing .gitattributes setting)

- setup.cfg
> fix setup.cfg issue with versioneer

- .travis.yml
- appveyor.yml
- src/conda_package_handling/conda_fmt.py
- src/conda_package_handling/tarball.py
in hopes of avoiding permission errors as seen in https://ci.appveyor.com/project/conda-forge/conda-feedstock/builds/25212968/job/73tl2u0vax8gj2p8#L1654
> copy temporary tarball instead of moving it

- src/conda_package_handling/api.py
- src/conda_package_handling/conda_fmt.py
- src/conda_package_handling/tarball.py
- src/conda_package_handling/utils.py
- tests/test_api.py
> TemporaryDirectory, now with 100% less infinite recursion

- news/no_print_skip
- src/conda_package_handling/api.py
> Skip converted

- news/TEMPLATE
- setup.cfg
- src/conda_package_handling/conda_fmt.py
- src/conda_package_handling/tarball.py
- src/conda_package_handling/utils.py
fixes https://github.com/conda/conda/issues/8807
> handle bad zip files by raising InvalidArchiveError

- news/tmpdir
- src/conda_package_handling/api.py
- src/conda_package_handling/conda_fmt.py
> create all tempdirs in the destination folder

- news/fallback
- src/conda_package_handling/api.py
- src/conda_package_handling/cli.py
- src/conda_package_handling/conda_fmt.py
- src/conda_package_handling/exceptions.py
- src/conda_package_handling/tarball.py
- tests/test_api.py
> Bz2 fallback

- news/cleanup
- src/conda_package_handling/api.py
- src/conda_package_handling/cli.py
- src/conda_package_handling/exceptions.py
- src/conda_package_handling/tarball.py
> fix up several small errors

- .travis.yml
- appveyor.yml
- conda.recipe/meta.yaml
- src/conda_package_handling/api.py
- src/conda_package_handling/utils.py
- tests/test_api.py
> tweak extract API to include prefix

- src/conda_package_handling/api.py
- src/conda_package_handling/cli.py
> Fixes for --process and --out-folder

- news/allow_symlinks
- news/fix_null_pointer
- news/process_and_out_folder_fixes
- src/conda_package_handling/validate.py
> Do not consider symlinks as missing

- .github/workflows/CI.yaml
- appveyor.yml
- news/0002-fix-binsort-mangling-symlinks.rst
- src/conda_package_handling/tarball.py
> Fix binsort's mangling of symlinks

- .github/workflows/CI.yaml
- conda.recipe/meta.yaml
- devtools/conda-envs/test_env.yaml
This was missing from the original GHA PR and should resolve having workable CI for future pull requests
Signed-off-by: Eli Uriegas <seemethere101@gmail.com>
> ci: Add test_env.yml

- .authors.yml
- .mailmap
- AUTHORS.rst
- CHANGELOG.rst
> Release 1.8.1

- src/conda_package_handling/cli.py
> Gracefully handle missing subcommands.

- .github/pull_request_template.md
Raised in https://github.com/conda/conda-build/pull/4538#issuecomment-1196933843 that we had both `PULL_REQUEST_TEMPALTE.md` and `pull_request_template.md` which obviously causes issues on case-insensitive filesystems. So we remove the older lowercase version.
> Remove old PR templates

- .authors.yml
- .mailmap
- AUTHORS.md
- CHANGELOG.md
conda-package-handling 1.9.0 release PR, following https://github.com/conda/conda/blob/main/RELEASE.md
> Release 1.9.0

- .authors.yml
- .mailmap
- AUTHORS.md
- Removed duplicate entries for Mike Sarahan in `git shortlog -se`.
- Removed duplicate entries for conda-bot in `AUTHORS.md`.
- Added missing contributor names.
> Deduplicate contributors

- .github/workflows/sphinx.yml
- Makefile
- README.md
- docs/api.md
- docs/conf.py
- docs/index.md
- docs/modules.md
- make.bat
- pyproject.toml
- requirements.txt
- setup.cfg
- setup.py
- src/conda_package_handling/api.py
- tests/test_api.py
- tests/test_interface.py
- update_usage.py
Includes the `api` module and the existing README.md
> Add sphinx documentation

- news/172-info-regex
- src/conda_package_handling/utils.py
This complex regex of what to include in info/ (not simply everything in the info/ folder) is obviously wrong. Improve it, at least a little.
#172
> include all LICENSE.* in info/ section

- conda.recipe/meta.yaml
- news/explicit-zstandard-dependency
Since we import zstandard (even though we try to work in "emergency mode" if it is not available), require it.
Fix #222
Update description.
> add zstandard dependency; update description

- MANIFEST.in
- news/163-manifest-in
Simplify MANIFEST.in which was pointing at non-existent files.
> empty MANIFEST.in seems to be doing the right thing

- src/conda_package_handling/tarball.py
- src/conda_package_handling/utils.py
I can't find a good reason to use `__file__` for `getLogger()` instead of the more popular `__name__`.
> use `__name__` for logging

- CHANGELOG.md
> celebrate new contributors

- .github/dependabot.yml
- .pre-commit-config.yaml
- docs/requirements.txt
Xref https://github.com/conda/conda-package-streaming/pull/116#issuecomment-2468776268
> Enable dependabot
